name: CI
on: push
jobs:
  test:
    name: Lint, Test, & Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install modules
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test:ci
      - name: Build Storybook
        run: yarn build:storybook
