name: CI
on: push
jobs:
  test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Run tests
        run: yarn test:ci
      - name: Build Storybook docs
        run: yarn build-storybook-docs
